// <auto-generated />
namespace TranCongMinh_BigSchool.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class IntinialModel2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(IntinialModel2));
        
        string IMigrationMetadata.Id
        {
            get { return "202206191753418_IntinialModel2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
